title: Minatour's blog page
description: This is where I upload all the write-ups for challenges or CTFs I do
theme: just-the-docs

url: https://minatour123.github.io/blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
